name: msm-Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Image Build
    runs-on: ubuntu-20.04

    strategy:
      max-parallel: 8
      matrix:
        device:
          - sm8350
          - mh2lm
          - betalm
          - nabu
          - vayu-huaxing
          - vayu-tianma
          - cepheus
          - hotdog
          - guacamole
          - guacamoleb
          - fajita
          - beryllium-ebbg
          - beryllium-tianma
          - polaris
          - perseus
          - mona
          - lisa
          - cheeseburger

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install required packages
        run: |
          sudo dpkg --add-architecture i386
          wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
          sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main'
          sudo apt-get update
          sudo apt-get -y install build-essential uuid-dev clang llvm iasl nasm gcc-aarch64-linux-gnu abootimg python3-distutils python3-pil python3-git gettext libgcc-s1:i386 libstdc++6:i386
          sudo apt-get -y --install-recommends install winehq-stable

      - name: Build an image for ${{ matrix.device }}
        run: |
          ./build.sh --device ${{ matrix.device }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.device }}
          path: ./*.img
